// Rebalance strategy templates. Each strategy is a pure object exposing
// shouldRebalance({now, lastRebalanceAt, currentWeightsBps, targetWeightsBps})
// plus {id, name, description}. All times are ms epoch. Weight maps are
// SYM -> integer bps (sum ~10000).

// Max absolute per-asset drift in bps between current and target.
export function maxDriftBps(currentWeightsBps, targetWeightsBps) {
    const syms = new Set([
        ...Object.keys(currentWeightsBps || {}),
        ...Object.keys(targetWeightsBps || {}),
    ]);
    let max = 0;
    for (const s of syms) {
        const c = currentWeightsBps?.[s] || 0;
        const t = targetWeightsBps?.[s] || 0;
        const d = Math.abs(c - t);
        if (d > max) max = d;
    }
    return max;
}

// Aggregate portfolio drift: 0.5 * sum over assets of |current - target|, i.e.
// total one-way turnover in bps. The anti-exploit measure: a single outlier
// name contributes only its own share, so one pumped asset cannot trip a
// portfolio-level band alone.
export function driftBpsAggregate(currentWeightsBps, targetWeightsBps) {
    const syms = new Set([
        ...Object.keys(currentWeightsBps || {}),
        ...Object.keys(targetWeightsBps || {}),
    ]);
    let sum = 0;
    for (const s of syms)
        sum += Math.abs((currentWeightsBps?.[s] || 0) - (targetWeightsBps?.[s] || 0));
    return Math.round(sum / 2);
}

// ---------------------------------------------------------------------------
// RebalanceSpec: a validated free-form trigger spec (prompt-generated by
// index/generate.mjs generateRebalanceStrategy). Shape:
//   {intervalMs, driftBps, takeProfitPct, cooldownMs, combine, maxStepMoveBps,
//    nameBreachBps, sectorDriftBps, drawdownPct, volBandPct, trendFlip,
//    relativeLagPct, note}
// Path-free triggers (interval, driftBps, nameBreachBps, sectorDriftBps,
// takeProfitPct) are enclave-reproducible today. History-based triggers
// (drawdownPct, volBandPct, trendFlip, relativeLagPct) run engine-side only
// until an attested NAV history is threaded into the sign envelope.
// ---------------------------------------------------------------------------

export const DEFAULT_MAX_STEP_MOVE_BPS = 2500;
export const DEFAULT_TREND_WINDOW = 20;

// -- Pure signal helpers. All take plain values, no engine state. --

// Max single-name |current - target| in bps (per-name cap breach).
export function nameBreachBps(currentWeightsBps, targetWeightsBps) {
    return maxDriftBps(currentWeightsBps, targetWeightsBps);
}

// Max sector-level |current - target| in bps over {sector: bps} maps.
export function sectorDrift(curBySector, tgtBySector) {
    return maxDriftBps(curBySector, tgtBySector);
}

// Fractional fall from the running peak: 0.08 = 8% below peak.
export function drawdown(peakNav, nav) {
    if (!(peakNav > 0) || !(nav > 0)) return 0;
    return Math.max(0, 1 - nav / peakNav);
}

// Realized volatility: stddev of per-tick returns over the last `window`
// returns of a NAV series (points are numbers or {nav}). Fraction per tick.
export function realizedVol(series, window = DEFAULT_TREND_WINDOW) {
    const navs = (series || []).map((p) => (typeof p === "number" ? p : p?.nav));
    const rets = [];
    for (let i = 1; i < navs.length; i++)
        if (navs[i - 1] > 0 && navs[i] > 0) rets.push(navs[i] / navs[i - 1] - 1);
    const r = rets.slice(-window);
    if (r.length < 2) return 0;
    const mean = r.reduce((a, x) => a + x, 0) / r.length;
    const varr = r.reduce((a, x) => a + (x - mean) ** 2, 0) / (r.length - 1);
    return Math.sqrt(varr);
}

// True when the latest NAV sits below its own moving average over the last
// `window` points (needs at least `window` points).
export function trendBelowMA(series, window = DEFAULT_TREND_WINDOW) {
    const navs = (series || [])
        .map((p) => (typeof p === "number" ? p : p?.nav))
        .filter((n) => n > 0);
    if (navs.length < window) return false;
    const tail = navs.slice(-window);
    const ma = tail.reduce((a, x) => a + x, 0) / tail.length;
    return navs[navs.length - 1] < ma;
}

// How far the index lags the benchmark, as a positive fraction (0 if ahead).
export function relativeLag(indexReturn, benchmarkReturn) {
    if (!Number.isFinite(indexReturn) || !Number.isFinite(benchmarkReturn)) return 0;
    return Math.max(0, benchmarkReturn - indexReturn);
}

const clampOrNull = (v, lo, hi) => {
    const n = Number(v);
    if (!Number.isFinite(n) || n <= 0) return null;
    return Math.min(hi, Math.max(lo, n));
};

// Fraction fields accept a fraction (0.08) or a percent (8) and clamp to
// (0, hiFrac]; percent form is divided by 100.
const fracOrNull = (v, hiFrac = 1) => {
    let n = clampOrNull(v, 0.0001, 100);
    if (n == null) return null;
    if (n > hiFrac) n /= 100;
    return Math.min(hiFrac, n);
};

// Coerce a raw object into a valid RebalanceSpec, or null when no trigger
// survives. takeProfitPct/drawdownPct/volBandPct/relativeLagPct accept a
// fraction (0.1) or a percent (10). trendFlip is a window in series points
// (true coerces to DEFAULT_TREND_WINDOW).
export function coerceRebalanceSpec(raw) {
    if (!raw || typeof raw !== "object") return null;
    const intervalMs = clampOrNull(raw.intervalMs, 60000, 31536000000); // 1m..365d
    const driftBps = clampOrNull(raw.driftBps, 10, 5000);
    let takeProfitPct = clampOrNull(raw.takeProfitPct, 0.0001, 100);
    if (takeProfitPct != null && takeProfitPct > 1) takeProfitPct /= 100; // percent form
    const cooldownMs = clampOrNull(raw.cooldownMs, 1000, 2592000000); // 1s..30d
    const nameBreach = clampOrNull(raw.nameBreachBps, 10, 5000);
    const sectorBand = clampOrNull(raw.sectorDriftBps, 10, 5000);
    const drawdownPct = fracOrNull(raw.drawdownPct, 0.95);
    const volBandPct = fracOrNull(raw.volBandPct, 0.95);
    const trendFlip =
        raw.trendFlip === true
            ? DEFAULT_TREND_WINDOW
            : clampOrNull(raw.trendFlip, 3, 500) != null
              ? Math.round(clampOrNull(raw.trendFlip, 3, 500))
              : null;
    const relativeLagPct = fracOrNull(raw.relativeLagPct, 0.95);
    const anyTrigger =
        intervalMs != null || driftBps != null || takeProfitPct != null ||
        nameBreach != null || sectorBand != null || drawdownPct != null ||
        volBandPct != null || trendFlip != null || relativeLagPct != null;
    if (!anyTrigger) return null;
    return {
        intervalMs,
        driftBps,
        takeProfitPct,
        cooldownMs,
        nameBreachBps: nameBreach,
        sectorDriftBps: sectorBand,
        drawdownPct,
        volBandPct,
        trendFlip,
        relativeLagPct,
        combine: raw.combine === "all" ? "all" : "any",
        maxStepMoveBps:
            clampOrNull(raw.maxStepMoveBps, 100, 10000) ?? DEFAULT_MAX_STEP_MOVE_BPS,
        note: String(raw.note || "").trim().slice(0, 240),
    };
}

// Evaluate a RebalanceSpec against a tick context -> {fire, reason}. Enabled
// triggers combine per spec.combine ("any" default), but cooldownMs ALWAYS
// gates: never fire while now - lastRebalanceAt < cooldownMs. Drift is the
// AGGREGATE portfolio drift (driftBpsAggregate), not a single asset's;
// nameBreachBps is the per-name band. History-based triggers (drawdownPct,
// volBandPct, trendFlip, relativeLagPct) need navSeries/peakNav/returns in ctx
// and silently stay cold when the engine did not supply them. reason names the
// FIRST firing signal.
export function evalRebalanceSpec(spec, ctx) {
    const {
        now,
        lastRebalanceAt,
        currentWeightsBps,
        targetWeightsBps,
        nav,
        lastRebalanceNav,
        navSeries,
        peakNav,
        sectorCurrentBps,
        sectorTargetBps,
        indexReturn,
        benchmarkReturn,
    } = ctx || {};
    if (
        spec.cooldownMs != null &&
        lastRebalanceAt != null &&
        now - lastRebalanceAt < spec.cooldownMs
    ) {
        return {
            fire: false,
            reason: `cooldown (${now - lastRebalanceAt}ms < ${spec.cooldownMs}ms)`,
        };
    }
    if (lastRebalanceAt == null) return {fire: true, reason: "first rebalance"};
    const checks = [];
    if (spec.intervalMs != null) {
        checks.push({
            hit: now - lastRebalanceAt >= spec.intervalMs,
            reason: `interval elapsed (${now - lastRebalanceAt}ms >= ${spec.intervalMs}ms)`,
        });
    }
    if (spec.driftBps != null) {
        const agg = driftBpsAggregate(currentWeightsBps, targetWeightsBps);
        checks.push({
            hit: agg >= spec.driftBps,
            reason: `aggregate drift ${agg}bps >= ${spec.driftBps}bps`,
        });
    }
    if (spec.nameBreachBps != null) {
        const b = nameBreachBps(currentWeightsBps, targetWeightsBps);
        checks.push({
            hit: b >= spec.nameBreachBps,
            reason: `name breach ${b}bps >= ${spec.nameBreachBps}bps`,
        });
    }
    if (spec.sectorDriftBps != null) {
        const d = sectorDrift(sectorCurrentBps || {}, sectorTargetBps || {});
        checks.push({
            hit: d >= spec.sectorDriftBps,
            reason: `sector drift ${d}bps >= ${spec.sectorDriftBps}bps`,
        });
    }
    if (spec.takeProfitPct != null) {
        const gain = lastRebalanceNav > 0 && nav > 0 ? nav / lastRebalanceNav - 1 : 0;
        checks.push({
            hit: gain >= spec.takeProfitPct,
            reason: `take-profit ${(gain * 100).toFixed(2)}% >= ${spec.takeProfitPct * 100}%`,
        });
    }
    if (spec.drawdownPct != null) {
        const dd = drawdown(peakNav, nav);
        checks.push({
            hit: dd >= spec.drawdownPct,
            reason: `drawdown ${(dd * 100).toFixed(2)}% >= ${spec.drawdownPct * 100}%`,
        });
    }
    if (spec.volBandPct != null) {
        const vol = realizedVol(navSeries, DEFAULT_TREND_WINDOW);
        checks.push({
            hit: vol >= spec.volBandPct,
            reason: `realized vol ${(vol * 100).toFixed(3)}% >= ${spec.volBandPct * 100}%`,
        });
    }
    if (spec.trendFlip != null) {
        checks.push({
            hit: trendBelowMA(navSeries, spec.trendFlip),
            reason: `trend flip: NAV below ${spec.trendFlip}-point MA`,
        });
    }
    if (spec.relativeLagPct != null) {
        const lag = relativeLag(indexReturn, benchmarkReturn);
        checks.push({
            hit: lag >= spec.relativeLagPct,
            reason: `relative lag ${(lag * 100).toFixed(2)}% >= ${spec.relativeLagPct * 100}% vs field avg`,
        });
    }
    if (!checks.length) return {fire: false, reason: "no triggers enabled"};
    const hits = checks.filter((c) => c.hit);
    const fire = spec.combine === "all" ? hits.length === checks.length : hits.length > 0;
    if (!fire) {
        return {
            fire: false,
            reason: spec.combine === "all" ? "not all triggers met" : "no trigger met",
        };
    }
    return {fire: true, reason: hits[0].reason};
}

// Interval strategy: rebalance once the interval has elapsed.
export function interval(intervalMs, meta = {}) {
    return {
        id: meta.id || `interval-${intervalMs}`,
        name: meta.name || `Every ${Math.round(intervalMs / 60000)}m`,
        description:
            meta.description ||
            `Rebalance when at least ${intervalMs}ms have passed.`,
        intervalMs,
        shouldRebalance({now, lastRebalanceAt}) {
            if (lastRebalanceAt == null) return true;
            return now - lastRebalanceAt >= intervalMs;
        },
    };
}

// Drift harness: rebalance when any asset drifts past the band.
export function drift(driftBps = 500, meta = {}) {
    return {
        id: meta.id || `drift-${driftBps}`,
        name: meta.name || `Drift ${driftBps / 100}%`,
        description:
            meta.description ||
            `Rebalance when max asset drift >= ${driftBps}bps.`,
        driftBps,
        shouldRebalance({currentWeightsBps, targetWeightsBps}) {
            return maxDriftBps(currentWeightsBps, targetWeightsBps) >= driftBps;
        },
    };
}

// Combined: rebalance on the interval, or early if the drift band is breached.
export function combined({intervalMs, driftBps = 500}, meta = {}) {
    return {
        id: meta.id || `combined-${intervalMs}-${driftBps}`,
        name:
            meta.name ||
            `Every ${Math.round(intervalMs / 60000)}m or ${driftBps / 100}% drift`,
        description:
            meta.description ||
            `Rebalance when ${intervalMs}ms elapsed OR drift >= ${driftBps}bps.`,
        intervalMs,
        driftBps,
        shouldRebalance({now, lastRebalanceAt, currentWeightsBps, targetWeightsBps}) {
            const elapsed =
                lastRebalanceAt == null || now - lastRebalanceAt >= intervalMs;
            const breached =
                maxDriftBps(currentWeightsBps, targetWeightsBps) >= driftBps;
            return elapsed || breached;
        },
    };
}

// Cooldown-gated drift: rebalance on a drift breach, but never more often than
// a minimum interval (a cooldown between rebalances).
export function cooldownDrift({driftBps = 500, cooldownMs}, meta = {}) {
    return {
        id: meta.id || `cooldown-drift-${driftBps}-${cooldownMs}`,
        name:
            meta.name ||
            `Drift ${driftBps / 100}% (${Math.round(cooldownMs / 60000)}m cooldown)`,
        description:
            meta.description ||
            `Rebalance on >= ${driftBps}bps drift, at most once per ${cooldownMs}ms.`,
        driftBps,
        cooldownMs,
        shouldRebalance({now, lastRebalanceAt, currentWeightsBps, targetWeightsBps}) {
            if (lastRebalanceAt == null) return true;
            if (now - lastRebalanceAt < cooldownMs) return false;
            return maxDriftBps(currentWeightsBps, targetWeightsBps) >= driftBps;
        },
    };
}

// Take-profit harness: rebalance when the index is up >= gainPct since its last
// rebalance. Needs {nav, lastRebalanceNav} in the tick context.
export function takeProfit(gainPct = 5, meta = {}) {
    const g = gainPct / 100;
    return {
        id: meta.id || `take-profit-${gainPct}`,
        name: meta.name || `Take-profit ${gainPct}%`,
        description:
            meta.description ||
            `Rebalance when NAV is up >= ${gainPct}% since the last rebalance.`,
        gainPct,
        shouldRebalance({nav, lastRebalanceNav}) {
            if (lastRebalanceNav == null || !(lastRebalanceNav > 0)) return true;
            return nav / lastRebalanceNav - 1 >= g;
        },
    };
}

// Ready-made templates. Add more intervals as one-liners.
export const intervalMinute = interval(60000, {
    id: "minute",
    name: "Minute",
});
export const intervalFiveMin2 = interval(300000, {
    id: "five-minute",
    name: "Five minute",
});
export const intervalTenMin2 = interval(600000, {
    id: "ten-minute",
    name: "Ten minute",
});
export const intervalThirtyMin = interval(1800000, {
    id: "thirty-minute",
    name: "Thirty minute",
});
export const intervalDaily = interval(86400000, {
    id: "daily",
    name: "Daily",
});
export const intervalHourly = interval(3600000, {
    id: "hourly",
    name: "Hourly",
});
// Calendar cadences (7/30/90 days).
export const intervalWeekly = interval(604800000, {
    id: "weekly",
    name: "Weekly",
    description: "Rebalance once every 7 days.",
});
export const intervalMonthly = interval(2592000000, {
    id: "monthly",
    name: "Monthly",
    description: "Rebalance once every 30 days.",
});
export const intervalQuarterly = interval(7776000000, {
    id: "quarterly",
    name: "Quarterly",
    description: "Rebalance once every 90 days.",
});
// Back-compat aliases (kept: the old ids stay valid).
export const intervalTenMin = intervalTenMin2;
export const intervalFiveMin = intervalFiveMin2;

// Drift harnesses at several bands.
export const drift2pct = drift(200, {id: "drift-2", name: "Drift 2%"});
export const drift5pct = drift(500, {id: "drift-5", name: "Drift 5%"});
export const drift10pct = drift(1000, {id: "drift-10", name: "Drift 10%"});
export const drift20pct = drift(2000, {id: "drift-20", name: "Drift 20%"});
// Keep the legacy id "drift-5pct" as an alias of drift-5.
export const drift5pctLegacy = drift(500, {id: "drift-5pct", name: "Drift 5%"});

// Combined interval+drift variants.
export const combinedHourlyDrift5 = combined(
    {intervalMs: 3600000, driftBps: 500},
    {id: "hourly-or-drift-5", name: "Hourly or 5% drift"}
);
// Keep the legacy id "hourly-or-drift" as an alias.
export const combinedHourlyDrift = combined(
    {intervalMs: 3600000, driftBps: 500},
    {id: "hourly-or-drift", name: "Hourly or 5% drift"}
);
export const combinedTenMinDrift2 = combined(
    {intervalMs: 600000, driftBps: 200},
    {id: "ten-minute-or-drift-2", name: "Ten minute or 2% drift"}
);
export const combinedThirtyMinDrift5 = combined(
    {intervalMs: 1800000, driftBps: 500},
    {id: "thirty-minute-or-drift-5", name: "Thirty minute or 5% drift"}
);
export const combinedFiveMinDrift2 = combined(
    {intervalMs: 300000, driftBps: 200},
    {id: "five-minute-or-drift-2", name: "Five minute or 2% drift"}
);

// Cooldown-gated drift.
export const cooldownDrift5Hourly = cooldownDrift(
    {driftBps: 500, cooldownMs: 3600000},
    {id: "cooldown-drift-5-hourly", name: "Drift 5% (hourly cooldown)"}
);
export const cooldownDrift2TenMin = cooldownDrift(
    {driftBps: 200, cooldownMs: 600000},
    {id: "cooldown-drift-2-ten-minute", name: "Drift 2% (ten-minute cooldown)"}
);

// Take-profit harnesses.
export const takeProfit5 = takeProfit(5, {id: "take-profit-5", name: "Take-profit 5%"});
export const takeProfit10 = takeProfit(10, {id: "take-profit-10", name: "Take-profit 10%"});

// Grouped for the FE picker: intervals, harnesses, combined.
export const STRATEGY_GROUPS = {
    intervals: [
        intervalMinute,
        intervalFiveMin2,
        intervalTenMin2,
        intervalThirtyMin,
        intervalHourly,
        intervalDaily,
        intervalWeekly,
        intervalMonthly,
        intervalQuarterly,
    ],
    harnesses: [
        drift2pct,
        drift5pct,
        drift10pct,
        drift20pct,
        cooldownDrift5Hourly,
        cooldownDrift2TenMin,
        takeProfit5,
        takeProfit10,
    ],
    combined: [
        combinedFiveMinDrift2,
        combinedTenMinDrift2,
        combinedThirtyMinDrift5,
        combinedHourlyDrift5,
    ],
};

export const STRATEGIES = Object.fromEntries(
    [
        ...STRATEGY_GROUPS.intervals,
        ...STRATEGY_GROUPS.harnesses,
        ...STRATEGY_GROUPS.combined,
        drift5pctLegacy, // legacy id alias
        combinedHourlyDrift, // legacy id alias
    ].map((s) => [s.id, s])
);

export function getStrategy(id) {
    const s = STRATEGIES[id];
    if (!s) throw new Error(`unknown strategy: ${id}`);
    return s;
}
